ALTER TABLE `Deployment` ADD COLUMN `jobId` VARCHAR(191) NULL,
ADD COLUMN `version` VARCHAR(191) NULL,
ADD COLUMN `error` TEXT NULL,
ADD COLUMN `duration` INTEGER NULL,
ADD COLUMN `startedAt` DATETIME(3) NULL,
ADD COLUMN `finishedAt` DATETIME(3) NULL;
